apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-lab-data
  labels:
    use: k8s-lab
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: <<created_data_dir>>
    type: Directory