apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-lab-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: local
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      use: "k8s-lab"
